[package]
name = "matrixmail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-imap = "0.9.1"
async-native-tls = "0.5.0"
async-std = { version = "1.12.0", features = ["attributes"] }
tokio = { version = "1.32.0", features = ["full"] }
