[package]
name = "matrixmail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-imap = "0.9.1"
async-native-tls = "0.5.0"
async-std = { version = "1.12.0", features = ["attributes"] }
futures = "0.3.28"
imap-proto = "0.16.2"
mail-parser = "0.8.2"
reqwest = "0.11.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
serde_yaml = "0.9.25"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
urlencoding = "2.1.3"
