version: "3.7"

services:
  matrixmail:
    image: atareao/matrixmail:latest
    container_name: matrixmail
    init: true
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml
